
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 2

[font.normal]
family = "ComicShannsMono Nerd Font"

[font.offset]
x = 0
y = 9

[terminal.shell]
program = "/run/current-system/sw/bin/zsh"

[window]
decorations = "buttonless"

[window.padding]
x = 20
y = 20

[colors]
draw_bold_text_with_bright_colors = false

[general]
import = ["/Users/eugebe/.config/alacritty/themes/one-monokai.toml"]

[terminal]
